### ISSUE TITLE
imageHighResolutionUrl returns null

### ISSUE THREAD

**Issue by eos1d3** [postaddictme/instagram-java-scraper#25]
From my test, imageHighResolutionUrl never works. It just returns null while high resolution image is there.

```
account = instagram.getAccountByUsername("eunjung.hahm");
List<Media> medias = instagram.getMedias("eunjung.hahm", 5);
for (Media medoa : medias) {
	System.out.println(medoa.imageHighResolutionUrl);
	System.out.println(medoa.imageLowResolutionUrl);
}
```

**Comment by eos1d3** [comment]
I found this problem is caused by using outdated maven in [https://github.com/postaddictme/instagram-java-scraper/issues/1](url)

Is there any latest maven information to use?

**Comment by igor-suhorukov** [comment]
Do you have the same issue by using latest development version of instagram-java-scraper?

**Comment by eos1d3** [comment]
This has a lot changes since Apr. I think the problem should be fixed. I do not use it and write my own library for Instagram. But this library is good and is very updated to new Instagram changes. I do recommend this one if you do not want to write it yourself.

**Comment by igor-suhorukov** [comment]
@eos1d3 thank you for response. Now this method data mapping located in [account-binding.json](https://github.com/postaddictme/instagram-java-scraper/blob/master/src/main/resources/me/postaddict/instagram/scraper/model/account-binding.json). Model changed significantly since april. So I think we can close this issue as "not applicable"
