### ISSUE TITLE
getMedia without hit, video

### ISSUE THREAD

**Issue by ggamzzak** [postaddictme/instagram-java-scraper#83]
I'm using SNAPSHOT at jitpack
I'm not found videoUrl, hitCount by getMedia(s) or null.
Please help me~

**Comment by igor-suhorukov** [comment]
@ggamzzak sorry but issue tickets is not stackoverflow... Just try to use repository text search before create new ticket.
try version 885979b instead of SNAPSHOT

media.getVideoUrl()
media.getVideoViewCount()
media.getCarouselMedia() ... getVideoUrl()
media.getCarouselMedia() ... getVideoViewCount()

https://github.com/postaddictme/instagram-java-scraper/blob/885979b22b05db7dfb51b3d9665ea224c4964396/src/main/java/me/postaddict/instagram/scraper/model/Media.java#L16

https://github.com/postaddictme/instagram-java-scraper/blob/885979b22b05db7dfb51b3d9665ea224c4964396/src/main/java/me/postaddict/instagram/scraper/model/CarouselResource.java#L21
